# -*- coding: utf-8 -*-
"""Gắn nhẵn cho dữ liệu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE88iVK16D_bsYvkr9uhNScBfKssRqJN
"""

import re
import requests
import pandas as pd


url = input('Nhập url trang:')
print("Loading url=", url)

r = re.search(r"i\.(\d+)\.(\d+)", url)
shop_id, item_id = r[1], r[2]
ratings_url = "https://shopee.vn/api/v2/item/get_ratings?filter=0&flag=1&itemid={item_id}&limit=20&offset={offset}&shopid={shop_id}&type=0"

offset = 0
d = {"username": [], "rating": [], "comment": []}
while True:
    data = requests.get(
        ratings_url.format(shop_id=shop_id, item_id=item_id, offset=offset)
    ).json()

    # uncomment this to print all data:
    # print(json.dumps(data, indent=4))
    # leng enumerate tra ket qua duoi dang liet ke
    i = 1
    for i, rating in enumerate(data["data"]["ratings"], 1):
        d["username"].append(rating["author_username"])
        d["rating"].append(rating["rating_star"])
        d["comment"].append(rating["comment"])

        print(rating["author_username"])
        print(rating["rating_star"])
        print(rating["comment"])
        print("-" * 100)

    if i % 20:
        break

    offset += 20
   

df = pd.DataFrame(d)
print(df)
df.to_csv("data.csv", index=False)

import pandas as pd
df = pd.read_csv("/content/data.csv")
df

df=df[['comment','rating']]
df

df=df.dropna()
df = df.reset_index(drop=True)
df

import numpy as np
df['rating']=df['rating'].astype(int) #chuyển rating  thành  int
df=df[df['rating']!=3]
df['label']=np.where(df['rating']>=4,1,0) #1-Positve,0-Negative

df['rating'].value_counts()

df

df=df[['comment','label']]
df

df.to_csv("out.csv", encoding='utf-8-sig')